---

- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include config override file, if it exists.
      include_vars: "{{ item }}"
      with_fileglob:
        - ../drupal-dockerizer.yml

  roles: []

  tasks:

    - name: Down all Docker containers.
      command: docker-compose -p {{ compose_project_name }} down --remove-orphans
      args:
        chdir: "{{ docker_runtime_dir }}"
