---

- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include config override file, if it exists.
      include_vars: "{{ item }}"
      with_fileglob:
        - config.yml

  roles: []

  tasks:
    - name: Stop all Docker containers.
      command: docker-compose down
      args:
        chdir: "{{ docker_runtime_dir }}"

    - name: Kill all Docker containers.
      command: docker-compose kill
      args:
        chdir: "{{ docker_runtime_dir }}"

    - name: Ensure runtime removed.
      become: true
      file:
        path: "{{ docker_runtime_dir }}"
        state: absent

    - name: Remove Host name from /etc/hosts
      become: true
      blockinfile:
        marker: "<!-- {mark} {{ compose_project_name }} ANSIBLE MANAGED BLOCK -->"
        state: absent
        path: /etc/hosts
        block: |
