---

- name: Add Drush as inventory host.
  add_host:
    name: "{{ compose_project_name }}-webserver"
    ansible_connection: docker
  changed_when: false

- name: Run command in container.
  delegate_to: "{{ compose_project_name }}-webserver"
  become: no
  raw: "drush -vy {{item}}"
  loop: "{{ drush_commands }}"
