name: Check php container build

on:
  pull_request:
    branches: [main]
    paths:
      - '**.Dockerfile'
  workflow_dispatch:

jobs:
  test_container_build:
    runs-on: ubuntu-20.04
    steps:
    - name: Cache Composer dependencies for improve speed
      uses: actions/cache@v2
      with:
        path: ~/.cache/composer
        key: ${{ runner.os }}-drupal

    - name: Get Drupal Project repository
      uses: actions/checkout@v2
      with:
        repository: 'drupal/recommended-project'
        path: './'
        ref: '9.2.x'

    - name: Run Composer install
      run: composer install --ignore-platform-reqs

    - name: Get Drupal Dockerizer repository
      uses: actions/checkout@v2
      with:
        path: '.drupal-dockerizer'

    - name: Create basic drupal-dockerizer.yml for php7.4-apache
      run: |
        echo "---" > drupal-dockerizer.yml
        echo "" >> drupal-dockerizer.yml
        echo "compose_project_name: drupal-project" >> drupal-dockerizer.yml
        echo "user_uid: $(id -u)" >> drupal-dockerizer.yml
        echo "user_gid: $(id -g)" >> drupal-dockerizer.yml
        echo "drupal_root_dir: $GITHUB_WORKSPACE" >> drupal-dockerizer.yml
        echo "expose_http_port: 80" >> drupal-dockerizer.yml
        echo "php_image: php7.4-apache" >> drupal-dockerizer.yml

    - name: Build php apache 7.4 container
      run: docker build -t php7.4-apache - < .drupal-dockerizer/images/php-apache/7.4-apache.Dockerfile

    - name: Run main playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: main.yml
        directory: .drupal-dockerizer
        options: |
          --verbose

    - name: Run drush-commands playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: drush-commands.yml
        directory: .drupal-dockerizer
        options: |
          --verbose

    - name: Check Drupal on php 7.4 version
      run: curl http://localhost | grep "Drupal"

    - name: Create basic drupal-dockerizer.yml for php7.3-apache
      run: |
        echo "---" > drupal-dockerizer.yml
        echo "" >> drupal-dockerizer.yml
        echo "compose_project_name: drupal-project" >> drupal-dockerizer.yml
        echo "user_uid: $(id -u)" >> drupal-dockerizer.yml
        echo "user_gid: $(id -g)" >> drupal-dockerizer.yml
        echo "drupal_root_dir: $GITHUB_WORKSPACE" >> drupal-dockerizer.yml
        echo "expose_http_port: 80" >> drupal-dockerizer.yml
        echo "php_image: php7.3-apache" >> drupal-dockerizer.yml

    - name: Build php apache 7.3 container
      run: docker build -t php7.3-apache  - < .drupal-dockerizer/images/php-apache/7.3-apache.Dockerfile

    - name: Run main playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: main.yml
        directory: .drupal-dockerizer
        options: |
          --verbose

    - name: Check Drupal on php 7.3 version
      run: curl http://localhost | grep "Drupal"
