name: Check adminer functionality

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '**.Dockerfile'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - name: Cache Composer dependencies for improve speed
      uses: actions/cache@v2
      with:
        path: ~/.cache/composer
        key: ${{ runner.os }}-drupal

    - name: Get Drupal Project repository
      uses: actions/checkout@v2
      with:
        repository: 'drupal/recommended-project'
        path: './'
        ref: '9.2.x'

    - name: Run Composer install
      run: composer install --ignore-platform-reqs

    - name: Get Drupal Dockerizer repository
      uses: actions/checkout@v2
      with:
        path: '.drupal-dockerizer'

    - name: Create basic drupal-dockerizer.yml
      run: |
        echo "---" > drupal-dockerizer.yml
        echo "" >> drupal-dockerizer.yml
        echo "compose_project_name: drupal-project" >> drupal-dockerizer.yml
        echo "user_uid: $(id -u)" >> drupal-dockerizer.yml
        echo "user_gid: $(id -g)" >> drupal-dockerizer.yml
        echo "drupal_root_dir: $GITHUB_WORKSPACE" >> drupal-dockerizer.yml
        echo "expose_http_port: 80" >> drupal-dockerizer.yml
        echo "install_adminer: true" >> drupal-dockerizer.yml
        echo "adminer_expose_port: 8085" >> drupal-dockerizer.yml

    - name: Run up playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: up.yml
        directory: .drupal-dockerizer
        options: |
          --verbose

    - name: Check Adminer
      run: curl http://localhost:8085
